services:
  streamlit:
    build:
      context: .
    container_name: used_car_price_predictor
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - RANDOM_SEED=${RANDOM_SEED:-47}
      - PYTHONPATH=/app
    working_dir: /app
    command: >
      streamlit run app/streamlit_app.py
      --server.port 8501
      --server.address 0.0.0.0
      --server.headless true